image: docker:latest

services:
  - docker:dind    

stages:
  - deploy

before_script:
  - docker version
  
build:
  stage: deploy
  script:
    - docker build --tag mymoney:latest .
    - docker stop $(docker ps -a -q) || true
    - docker run --restart unless-stopped -p 80:80 -d mymoney:latest
    - docker system prune -a -f