image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
  - docker:dind    

stages:
  - deploy

before_script:
  - docker version
  
build:
  stage: deploy
  script:
    - docker image prune -f
    - docker build --tag nginx:1.5 .
    - docker stop $(docker ps -a -q)
    - docker rm $(docker ps -a -q)
    - docker run --restart=always -p 80:80 -d nginx:1.5