image: docker:latest

services:
  - docker:dind    

before_script:
  - docker info
  - docker version
  
build:
  script:
    - docker image prune -f
    - docker build --tag nginx:1.5 .
    - docker run -p 80:80 -d nginx:1.5