image: docker:latest

services:
  - docker:dind    

stages:
  - deploy

before_script:
  - docker version
  
build:
  stage: deploy
  script:
    - docker image prune -f
    - docker build --tag nginx:1.5 .
    - docker run -p 80:80 -d nginx:1.5